CREATE TABLE [dbo].[IF_ECOUNT_ES303M](
	[VERSION] [varchar](14) NOT NULL,
	[PRG_TYPE] [varchar](8) NOT NULL,
	[EDIT_TYPE] [nvarchar](100) NOT NULL,
	[KEY1] [nvarchar](100) NOT NULL,
	[KEY2] [nvarchar](100) NOT NULL,
	[ROW_NO] [int] NOT NULL,
	[COMMENT] [nvarchar](100) NULL,
	[COL0] [nvarchar](1000) NULL,
	[COL1] [nvarchar](1000) NULL,
	[COL2] [nvarchar](1000) NULL,
	[COL3] [nvarchar](1000) NULL,
	[COL4] [nvarchar](1000) NULL,
	[COL5] [nvarchar](1000) NULL,
 CONSTRAINT [PK_IF_ECOUNT_ES303M] PRIMARY KEY CLUSTERED 
(
	[VERSION] ASC,
	[PRG_TYPE] ASC,
	[EDIT_TYPE] ASC,
	[KEY1] ASC,
	[KEY2] ASC,
	[ROW_NO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]